### ISSUE TITLE
You have your node online

### ISSUE THREAD

**Issue by aurea1123** [Guinea1/AnotherScryptCoin#2]

**Comment by Guinea1** [comment]
Yeah it seems that while the node is online, it is having stale block issues (that are not fixed by mining), which means that I will have to set up a second node most likely, I'll get to it when I have some free time :thumbsup:

![Screenshot (39)](https://user-images.githubusercontent.com/47433993/152870991-d552797f-3c16-42a2-a0b9-6286c867e2f7.png)

**Comment by Guinea1** [comment]
Please see the readme. I am archiving this again.
